config/routes.rb
Rails.application.routes.draw do
  get "/", to: "welcome#show"
  get "/Folio", to: "users#index", as: "folio"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # public folders and files
  get '/public', to: "public#index"
  namespace :public do
    resources :folders, path: :f, only: [:show]
    resources :uploads, path: :u, only: [:show]
  end

  # admin
  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :users, only: [:update, :show]
  end

  # password reset
  get '/password', to: 'passwords#new'
  post '/password', to: 'passwords#create'
  get '/password/update', to: 'passwords#edit', as: "reset_password"
  put '/password/update', to: 'passwords#update', as: "update_password"

  # users
  resources :users, path: '', only: [:show, :edit, :update]
  resources :users, only: [:new, :create]

  # folders
  resources :folders, path: "f/:id", only: [:new, :create]
  resources :folders, path: :f, only: [:show, :update, :destroy] do
    get "/share", to: "folders/collaborations#new"
    post "/share", to: "folders/collaborations#create"
  end
  get "/f/share/:id", to: "folders/collaborations#show", as: "shared"

  get "/f/:id/download", to: "folders/download#index", as: "folder_download"

  # uploads, comments & download
  resources :uploads, path: :u, only: [:new, :create, :show, :update, :destroy]
  get "/u/:id/download", to: "uploads/download#index", as: "upload_download"
  resources :uploads, path: :u, only: [:show] do
    resources :comments, only: [:create]
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
before_action :authorize!

  def index
    @uploads = Upload.all
    @users = User.all
  end
end

app/views/admin/dashboard/index.html.erb
<h4 align="center">Admin Dashboard</h4>
<h5 align="center">All files</h5>
<div "container" id="main">
<div class="container" id="allfiles" style="overflow:scroll; height:400px;">
  <div class="row">
    <div class="col m12">
        <table class="bordered highlight">
         <thead>
            <tr>
              <th>User</th>
              <th>File Name</th>
              <th>File Type</th>
              <th>Delete<th>
            </tr>
          </thead>
          <tbody>
            <% @uploads.each do |upload|%>
              <tr>
                <% if upload.user_activated? %>
                <td> <%= upload.user.username%></td>
                <td> <%=link_to "#{upload.name}", upload_path(upload)%></td>
                <td> <%= upload.content_type%></td>
                <td><%= link_to "delete", upload_path(upload), method: :delete%>
                <% else%>
                <% end %>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <br>
  <br>
  <h5 align="center">All Users</h5>
  <div class="container" id="allusers" style="overflow:scroll; height:400px;">
    <div class="row">
      <div class="col m12">
          <table class="bordered highlight">
            <thead>
              <tr>
                <th>UserName</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Status</th>
                <th>Change Status</th>
              </tr>
            </thead>
              <% @users.each do |user|%>
            <tbody>
              <tr>
                <td><%=user.username%></td>
                <td><%=user.first_name%></td>
                <td><%=user.last_name%></td>
                <td><%=user.email%></td>
                <td><%=user.status%></td>
                <% if user.activated_user?%>
                <td><%= link_to "deactivate", admin_user_path(user), method: :put%>
                <%else user.deactivated_user?%>
              <td><%= link_to "activate", admin_user_path(user), method: :put%>
                <%end%>
              </tr>
              <%end%>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>