config/routes.rb
Rails.application.routes.draw do
  get "/", to: "welcome#show"
  get "/Folio", to: "users#index", as: "folio"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # public folders and files
  get '/public', to: "public#index"
  namespace :public do
    resources :folders, path: :f, only: [:show]
    resources :uploads, path: :u, only: [:show]
  end

  # admin
  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :users, only: [:update, :show]
  end

  # password reset
  get '/password', to: 'passwords#new'
  post '/password', to: 'passwords#create'
  get '/password/update', to: 'passwords#edit', as: "reset_password"
  put '/password/update', to: 'passwords#update', as: "update_password"

  # users
  resources :users, path: '', only: [:show, :edit, :update]
  resources :users, only: [:new, :create]

  # folders
  resources :folders, path: "f/:id", only: [:new, :create]
  resources :folders, path: :f, only: [:show, :update, :destroy] do
    get "/share", to: "folders/collaborations#new"
    post "/share", to: "folders/collaborations#create"
  end
  get "/f/share/:id", to: "folders/collaborations#show", as: "shared"

  get "/f/:id/download", to: "folders/download#index", as: "folder_download"

  # uploads, comments & download
  resources :uploads, path: :u, only: [:new, :create, :show, :update, :destroy]
  get "/u/:id/download", to: "uploads/download#index", as: "upload_download"
  resources :uploads, path: :u, only: [:show] do
    resources :comments, only: [:create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
  has_many :folders
  has_many :uploads, through: :folders
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :collaborations, dependent: :destroy
  has_many :shared_on, through: :collaborations, source: :folder

  validates :username, :email, :cellphone, presence: true, uniqueness: true
  validates :first_name, :last_name, :password_digest, presence: true

  after_create :create_root, :registered_user

  enum status: [:activated, :deactivated]

  def root_folder
    folders.find_by(parent_id: nil)
  end

  def create_root
    folders.create!(name: "Folio")
  end

  def create_reset_digest
    password_token = rand(1000..10000).to_s
    self.update_attribute(:reset_token, password_token)
    self.save
  end

  def admin?
    roles.exists?(name: "admin")
  end

  def activated_user?
    self.status == "activated"
  end

  def deactivated_user?
    self.status == "deactivated"
  end

  def registered_user
    role = Role.find_or_create_by(name: 'registered user')
    self.roles << role
  end

  def activate
    self.update(status: "activated")
  end

  def deactivate
    self.update(status: "deactivated")
  end

  def full_name
    first_name.capitalize + " " + last_name.capitalize
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def update
   @user = User.find(params[:id])
   if @user.activated_user?
     @user.deactivate
    else
      @user.deactivated_user?
      @user.activate
    end
    redirect_back(fallback_location: "admin/dashboard")
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize!, only: [:show, :index, :edit, :update]
  after_action :current_folder, only: :index

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to folio_path
    else
      render :new
    end
  end

  def show
  end

  def index
    session[:current_folder_id] = current_user.root_folder.id
    @folder = Folder.new
    @file = Upload.new
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    @user.update_attribute(:password, params[:user][:new_password])
    flash[:success] = "Account Successfully Updated!"
    redirect_to folio_path
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:username, :first_name, :last_name, :email, :cellphone, :password)
  end
end

app/views/users/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2 class="center">Update Your Account</h1>

  <div class="row center">
    <%= form_for @user, class: "col s12" do |f| %>
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">perm_identity</i>
          <%= f.text_field :first_name, placeholder: "First Name", id: "icon-prefix" %>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">perm_identity</i>
          <%= f.text_field :last_name, placeholder: "Last Name", id: "icon-prefix" %>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">email</i>
          <%= f.text_field :email, placeholder: "Email", id: "icon-prefix" %>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">phone</i>
          <%= f.text_field :cellphone, placeholder: "Cell Phone Number", id: "icon-prefix" %>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">lock</i>
          <%= f.password_field :password, placeholder: "Password", id: "icon-prefix"%>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">security</i>
          <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", id: "icon-prefix" %>
        </div>
        <%= f.submit "Update Account", class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1><%= current_user.first_name %>'s Folio</h1>

<table>
  <tr>
    <td>
      <%= link_to "Create New Folder", new_folder_path(current_folder), class: "btn" %>
    </td>
    <td>
      <%= render partial: "shared/upload_form" %>
    </td>
  </tr>
</table>
<h5>My Folios</h5>
<br>
<div class="breadcrumb_folio">
  <%= render partial: "shared/breadcrumbs" %>
</div>
<div class="download_folio_icon">
  <%= link_to folder_download_path(current_folder) do %><span><i class="material-icons">file_download</i></span><% end %>
</div>
<br>
<%= render partial: "shared/owned_table" %>

<% unless current_user.shared_on.first.nil? %>
  <%= render partial: "shared/shared_table" %>
<% end %>

app/views/users/new.html.erb
<div class="sign-up">
  <h2 class="center">Create Your Folio</h2>

  <div class="row center">
    <%= form_for @user, class: "col s12" do |f| %>
    <%= render 'users/error_messages', object: f.object %>
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">account_circle</i>
          <%= f.text_field :username, placeholder: "Username", id: "icon-prefix" %>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">perm_identity</i>
          <%= f.text_field :first_name, placeholder: "First Name", id: "icon-prefix" %>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">perm_identity</i>
          <%= f.text_field :last_name, placeholder: "Last Name", id: "icon-prefix" %>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">email</i>
          <%= f.text_field :email, placeholder: "Email", id: "icon-prefix" %>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">phone</i>
          <%= f.text_field :cellphone, placeholder: "Cell Phone Number", id: "icon-prefix" %>
        </div>
        <div class="input-field col s12">
          <i class="material-icons prefix">lock</i>
          <%= f.password_field :password, placeholder: "Password", id: "icon-prefix"%>
        </div>
        <div class="input-field col s12">
          <i class="material-icons prefix">security</i>
          <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", id: "icon-prefix" %>
        </div>
        <%= f.submit "Start Sharing", class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Account Info: <%= current_user.full_name %></h1>
<%= link_to material_icon.mode_edit, edit_user_path(current_user), class: "btn-floating btn-large red" %>
<div class="container">
<ul class="collection">
    <li class="collection-item avatar">
      <i class="material-icons circle">assignment_ind</i>
      <span class="title">Username</span>
      <p><%= current_user.username %></p>
    </li>
    <li class="collection-item avatar">
      <i class="material-icons circle">email</i>
      <span class="title">E-mail</span>
      <p><%= current_user.email %></p>
    </li>
  </ul>
</div>