config/routes.rb
Rails.application.routes.draw do
  get "/", to: "welcome#show"
  get "/Folio", to: "users#index", as: "folio"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # public folders and files
  get '/public', to: "public#index"
  namespace :public do
    resources :folders, path: :f, only: [:show]
    resources :uploads, path: :u, only: [:show]
  end

  # admin
  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :users, only: [:update, :show]
  end

  # password reset
  get '/password', to: 'passwords#new'
  post '/password', to: 'passwords#create'
  get '/password/update', to: 'passwords#edit', as: "reset_password"
  put '/password/update', to: 'passwords#update', as: "update_password"

  # users
  resources :users, path: '', only: [:show, :edit, :update]
  resources :users, only: [:new, :create]

  # folders
  resources :folders, path: "f/:id", only: [:new, :create]
  resources :folders, path: :f, only: [:show, :update, :destroy] do
    get "/share", to: "folders/collaborations#new"
    post "/share", to: "folders/collaborations#create"
  end
  get "/f/share/:id", to: "folders/collaborations#show", as: "shared"

  get "/f/:id/download", to: "folders/download#index", as: "folder_download"

  # uploads, comments & download
  resources :uploads, path: :u, only: [:new, :create, :show, :update, :destroy]
  get "/u/:id/download", to: "uploads/download#index", as: "upload_download"
  resources :uploads, path: :u, only: [:show] do
    resources :comments, only: [:create]
  end

end

app/views/shared/_breadcrumbs.html.erb
<div class="breadcrumbs">
  <div class="box">
    <%= link_to "Folio", folio_path %>
  </div>
  <% current_folder.ancestors.each do |f| %>
  <% unless f.name == "Folio" %>
    <div class="box">
        <%= link_to f.name, folder_path(f) %>
    </div>
    <% end %>
  <% end %>
  <% unless current_folder.name == "Folio" %>
    <div class="box">
        <%= current_folder.name %>
    </div>
  <% end %>
</div>

app/views/shared/_comments_section.html.erb
<div class="comment_section">
  <h3 class="comment_header">Comments</h3>
  <% if current_user %>
    <%= render partial: "comments/form" %>
  <% end %>
  <h5>Total Comments (<%= @upload.comments.size %>)</h5>
  <% @upload.comments.each do |comment| %>
    <div class="one_comment">
      <strong><%= comment.user.username %> </strong>
      <p><%= comment.content %></p>
      <p>(Posted on <%= comment.created_at.strftime("%d %b. %Y") %>)</p>
    </div>
  <% end %>
</div>

app/views/shared/_folder_form.html.erb
folder form goes here

app/views/shared/_guest_nav.html.erb
<div class="navbar-fixed">
    <nav>
      <div class="container">
        <div class="nav-wrapper">
          <%= link_to "Folio Share", "/", class: "brand-logo" %>
          <ul class="right hide-on-med-and-down">
            <li><%= link_to "Public Files", public_path%></li>
            <li><%= link_to "Login", login_path%></li>
            <li><%= link_to "Signup", new_user_path %></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>

app/views/shared/_owned_table.html.erb
<table class="responsive-table bordered highlight table_center">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>File Size</th>
      <th>File Type</th>
      <th>Share</th>
      <th>Privacy Status</th>
      <th></th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% current_folder.children.each do |child| %>
      <tr id=<%= child.row_id %>>
        <td>
          <% if child.class == Upload %>
            <i class="material-icons">description</i>
          <% elsif child.collaborations.count > 0 %>
            <i class="material-icons">folder_shared</i>
          <% else %>
            <i class="material-icons">folder</i>
          <% end %>
        </td>
        <td>
          <%= link_to child.name, folder_or_upload_path(child) %>
        </td>
        <td>
          <%= number_to_human_size(child.size) %>
        </td>
        <td>
          <%= child.content_type %>
        </td>
        <td>
          <% if child.class == Folder %>
            <%= button_to "Share Folder", folder_share_path(child), method: :get%>
          <% end %>
        </td>
        <td>
          <% if child.display_privacy == "Private" %>
            <i class="material-icons private-icon">visibility_off</i>
          <% else %>
            <i class="material-icons public-icon">visibility</i>
          <% end %>
        </td>
        <td>
          <%= button_to "Make #{child.opposite_privacy}", folder_or_upload_path(child), class: child.privacy_button, method: :put %>
        </td>
        <td>
          <i class="material-icons">delete</i>
          <%= button_to "Delete", folder_or_upload_path(child), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_public_table.html.erb
<table class="responsive-table bordered highlight">
  <thead>
    <tr>
      <th>Name</th>
      <th>File Size</th>
      <th>File Type</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <% current_folder.children.each do |child| %>
        <td>
          <%= link_to child.name, public_folder_or_upload_path(child) %>
        </td>
        <td>
          <%= child.size %>
        </td>
        <td>
          <%= child.content_type %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_shared_table.html.erb
<div class="shared-table">
  <br/>

  <h5>Folios Shared With Me</h5>
  <table class="responsive-table bordered highlight">
    <thead>
      <tr>
        <th class="table_header_center"></th>
        <th class="table_header_center">Name</th>
        <th class="table_header_center">Owner</th>
      </tr>
    </thead>

    <tbody>
        <% current_user.shared_on.each do |folder| %>
        <tr>
          <td class="table_data_center"><i class="material-icons">folder_shared</i></td>
          <td class="table_data_center"><%= link_to folder.name, shared_path(folder) %></td>
          <td class="table_data_center"><%= folder.owner.username %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_upload_form.html.erb
<%= form_for @file do |f| %>
<div class="upload_file_form">
  <%= f.file_field :attachment %>
  <%= f.text_field :folder_id, value: "#{current_folder.id}", type: :hidden %>
  <br>
  <%= f.submit "Upload File" %>
</div>
<% end %>

app/views/shared/_user_nav.html.erb
<div class="navbar-fixed">
    <nav>
      <div class="container">
        <div class="nav-wrapper">
          <%= link_to "Folio Share", folio_path, class: "brand-logo" %>
         <ul class="right">
          <li><%= link_to "Public Files", public_path%></li>
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1" data-beloworigin="true"><%= current_user.full_name %><i class="material-icons right">arrow_drop_down</i></a></li>
          <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        </ul>
      </div>
     </div>
    </nav>
  </div>

  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <li><%= link_to "Account Details", user_path(current_user) %></li>
    <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
    <%if current_user.admin?%>
      <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>
    <% end %>
  </ul>